### PR TITLE
modification with db name.

### PR DESCRIPTION
**Pull request by nxajh**

### CODE REVIEW

**Comment by nladuo** [comment]
admin数据库是做用户名密码验证的数据库，不是用于保存爬取数据的config['db_name']。

**Comment by nxajh** [comment]
So, you use 2 databases in your program, db_name is for data storage, admin is for user/pass validation.
I am quite confused, why don't you use the same database?

**Comment by nxajh** [comment]
Oh, I got you.
So, the admin database is used for validating the user has enough permission, right?
But I don't think every user has the permission for admin database.
So, I think what should be verified is only the permission of the data storage database.

**Comment by nladuo** [comment]
I look up the PyMongo docs, you are right.

**Pull request merged**
